# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: yarn install --pure-lockfile
            - run: yarn prettier
            - name: Run eslint
              uses: a-b-r-o-w-n/eslint-action@v1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  files: 'components/**/*'
                  extensions: '.js,.ts'
            - run: yarn build
            - run: pm2 reload next-js
              env:
                CI: true
